/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - Measure and summarize data using aggregate functions.
    - Compare results across categories to reveal distribution patterns and trends.

SQL Functions Used:
    - SUM()
    - COUNT()
    - AVG()
    - GROUP BY
    - ORDER BY
===============================================================================
*/

-- Count total customers grouped by country
SELECT 
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Count total customers grouped by gender
SELECT 
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Count total products grouped by category
SELECT
category,
COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- Calculate the average product cost per category
SELECT
category,
AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- Calculate total revenue generated per product category
SELECT
p.category,
SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_products AS p
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Calculate total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c 
ON c.customer_key = s.customer_key
GROUP BY 
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue;

-- Calculate the distribution of sold items across countries
SELECT
c.country,
SUM(s.quantity) AS sold_items
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY sold_items DESC;
